# Generated by Django 5.2.14 on 2026-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: square JPG, PNG, or WebP image, at least 600x600px.', null=True, upload_to='categories/'),
        ),
    ]
