# Generated by Django 5.2.14 on 2026-05-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='password_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
