# Generated by Django 5.2.14 on 2026-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Recommended: JPG, PNG, or WebP. Use a wide campaign banner around 1920x700px.', null=True, upload_to='campaigns/'),
        ),
    ]
