# Generated by Django 5.2.14 on 2026-05-29 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Optional numeric discount badge shown on assigned product images. Example: enter 10 for 10% OFF.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
