# Generated by Django 5.2.14 on 2026-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='background_image',
            field=models.ImageField(help_text='Recommended: JPG, PNG, or WebP. Use a wide banner around 1920x700px. Avoid TIFF for browser display.', upload_to='banners/'),
        ),
    ]
