# Generated by Django 5.2.14 on 2026-05-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0002_alter_banner_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#e11d48', help_text='Accent color for discount badges and highlights.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='body_bg_color',
            field=models.CharField(default='#f8fafc', help_text='Main page background color.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(default='#047857', help_text='Main button background color.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_hover_bg_color',
            field=models.CharField(default='#065f46', help_text='Main button hover background color.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_text_color',
            field=models.CharField(default='#ffffff', help_text='Main button text color.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_family',
            field=models.CharField(choices=[('Inter, Arial, sans-serif', 'Inter / Arial'), ('Poppins, Arial, sans-serif', 'Poppins'), ('Roboto, Arial, sans-serif', 'Roboto'), ('Lato, Arial, sans-serif', 'Lato'), ('Georgia, serif', 'Georgia'), ("system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", 'System UI')], default='Inter, Arial, sans-serif', help_text='Controls the main font family across the storefront.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_bg_color',
            field=models.CharField(default='#ffffff', help_text='Footer background color.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_color',
            field=models.CharField(default='#475569', help_text='Footer text color.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='link_color',
            field=models.CharField(default='#047857', help_text='Link and brand text color.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_bg_color',
            field=models.CharField(default='#ffffff', help_text='Navbar background color.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_text_color',
            field=models.CharField(default='#0f172a', help_text='Navbar text color.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#047857', help_text='Primary brand color. Example: #047857', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#0f172a', help_text='Secondary dark color. Example: #0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_color',
            field=models.CharField(default='#0f172a', help_text='Main text color.', max_length=7),
        ),
    ]
