# Generated by Django 5.2.14 on 2026-05-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0003_sitesettings_accent_color_sitesettings_body_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='navbar_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='navbar_text_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='text_color',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='body_text_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_border_color',
            field=models.CharField(default='#047857', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_hover_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_heading_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_link_color',
            field=models.CharField(default='#cbd5e1', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_link_hover_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_social_hover_color',
            field=models.CharField(default='#047857', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_social_icon_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_bg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_cart_bg_color',
            field=models.CharField(default='#047857', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_cart_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_nav_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_nav_hover_color',
            field=models.CharField(default='#047857', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_text_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='heading_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='link_hover_color',
            field=models.CharField(default='#065f46', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_menu_icon_color',
            field=models.CharField(default='#0f172a', help_text='Burger menu icon color', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#e11d48', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='body_bg_color',
            field=models.CharField(default='#f8fafc', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(default='#047857', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_hover_bg_color',
            field=models.CharField(default='#065f46', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font_family',
            field=models.CharField(choices=[('Inter, Arial, sans-serif', 'Inter / Arial'), ('Poppins, Arial, sans-serif', 'Poppins'), ('Roboto, Arial, sans-serif', 'Roboto'), ('Lato, Arial, sans-serif', 'Lato'), ('Georgia, serif', 'Georgia'), ('system-ui, sans-serif', 'System UI')], default='Inter, Arial, sans-serif', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_bg_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_color',
            field=models.CharField(default='#cbd5e1', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='link_color',
            field=models.CharField(default='#047857', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#047857', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
    ]
