# Generated by Django 5.2.14 on 2026-05-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0004_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='font_family',
            field=models.CharField(choices=[('Inter, Arial, sans-serif', 'Inter / Arial'), ('Poppins, Arial, sans-serif', 'Poppins'), ('Roboto, Arial, sans-serif', 'Roboto'), ('Lato, Arial, sans-serif', 'Lato'), ('Georgia, serif', 'Georgia'), ('system-ui, sans-serif', 'System UI')], default='Poppins, Arial, sans-serif', max_length=120),
        ),
    ]
