# Generated by Django 5.2.14 on 2026-05-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0005_alter_sitesettings_font_family'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='button_bg_color',
            new_name='body_button_bg_color',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='button_border_color',
            new_name='body_button_border_color',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='button_hover_bg_color',
            new_name='body_button_hover_bg_color',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='button_hover_text_color',
            new_name='body_button_hover_text_color',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='button_text_color',
            new_name='body_button_text_color',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='footer_social_hover_color',
            new_name='footer_social_icon_hover_bg',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_social_icon_hover_text',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_cart_hover_bg_color',
            field=models.CharField(default='#065f46', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_menu_icon_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
    ]
