# Generated by Django 5.2.14 on 2026-05-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0006_rename_button_bg_color_sitesettings_body_button_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_button_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_text_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_cash_on_delivery_info',
            field=models.BooleanField(default=True, help_text="Show 'Cash on delivery' message"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_easy_returns_info',
            field=models.BooleanField(default=True, help_text="Show 'Easy returns' message"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_free_shipping_info',
            field=models.BooleanField(default=True, help_text="Show 'Free shipping' message"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_product_shipping_info',
            field=models.BooleanField(default=True, help_text='Show shipping and returns information on product detail pages'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_bg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_heading_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_link_color',
            field=models.CharField(default='#047857', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_link_hover_color',
            field=models.CharField(default='#065f46', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_icon_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_color',
            field=models.CharField(default='#475569', max_length=7),
        ),
    ]
