# Generated by Django 5.2.14 on 2026-05-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0007_sitesettings_banner_button_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='banner_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
