# Generated by Django 5.2.14 on 2026-05-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0008_alter_sitesettings_banner_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Dhaka, Outside Dhaka', max_length=100, unique=True)),
                ('courier_fee', models.DecimalField(decimal_places=2, help_text='Courier fee in ৳', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Area',
                'verbose_name_plural': 'Shipping Areas',
                'ordering': ['name'],
            },
        ),
    ]
