# Generated by Django 5.2.14 on 2026-05-31 09:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_manager", "0014_add_max_orders_per_phone_per_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="cod_order_max_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Maximum order total allowed for Cash on Delivery. Set to 0 to allow COD for all orders.",
                max_digits=10,
            ),
        ),
    ]
