# Generated by Django 5.2.14 on 2026-05-31 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_manager", "0015_alter_sitesettings_cod_order_max_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="banner_button_text_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="banner_text_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="body_bg_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="body_button_bg_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="body_button_border_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="body_button_hover_bg_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="body_button_hover_text_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="body_button_text_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="body_text_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="font_family",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_bg_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_heading_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_link_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_link_hover_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_social_icon_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_social_icon_hover_bg",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_social_icon_hover_text",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_text_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="header_bg_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="header_cart_bg_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="header_cart_hover_bg_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="header_cart_text_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="header_nav_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="header_nav_hover_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="header_text_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="heading_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="link_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="link_hover_color",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="mobile_menu_icon_color",
        ),
        migrations.AlterField(
            model_name="banner",
            name="button_url",
            field=models.CharField(
                blank=True,
                help_text="Use full absolute URLs starting with http:// or https://",
                max_length=255,
                validators=[
                    django.core.validators.URLValidator(schemes=["http", "https"])
                ],
            ),
        ),
    ]
