# Generated by Django 5.2.14 on 2026-05-31 01:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_promocode_order_discount_amount_order_promo_code_and_more'),
        ('settings_manager', '0009_shippingarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='settings_manager.shippingarea'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
