# Generated by Django 5.2.14 on 2026-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_default_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_guide',
            field=models.ImageField(blank=True, help_text='Optional. Upload a clear JPG, PNG, or WebP size guide image.', null=True, upload_to='size-guides/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Recommended: square JPG, PNG, or WebP product image, at least 800x800px.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Recommended: JPG, PNG, or WebP image matching the main product image ratio.', upload_to='products/gallery/'),
        ),
    ]
