# Generated by Django 5.2.14 on 2026-05-31 01:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_size_guide_alter_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed product description with rich text formatting.', null=True, verbose_name='Full Description'),
        ),
    ]
